# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 23:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_selector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_contacted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
